export const RESET_STATE = 'RESET_STATE'
export const QUESTION_ADD = 'QUESTION_ADD';
export const QUESTION_REMOVE = 'QUESTION_REMOVE';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';